import Link from "next/link";
import { OperationsFrame } from "@/components/OperationsFrame";
import { requireAuth } from "@/lib/auth/session";
import { can } from "@/lib/auth/policy";
import { listEmployees, listProjects, operationScope, PROJECT_STATUSES } from "@/lib/operations";

export const dynamic = "force-dynamic";

export default async function ProjectsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const auth = await requireAuth();
  if (!operationScope(auth, "projects.view")) return <OperationsFrame auth={auth} active="/projects"><div className="page"><div className="form-alert">You do not have permission to view projects.</div></div></OperationsFrame>;
  const [projects, params] = await Promise.all([listProjects(auth), searchParams]);
  const manage = can(auth, "projects.manage");
  const employees = manage && operationScope(auth, "employees.view") ? await listEmployees(auth) : [];
  const editId = typeof params.edit === "string" ? params.edit : "";
  const selected = projects.find(project => project.id === editId);
  return <OperationsFrame auth={auth} active="/projects"><div className="page operations-page"><section className="welcome page-title"><div><p className="eyebrow">PORTFOLIO</p><h1>Projects</h1><p>Persistent jobsites, leadership assignments, dates, status, and project notes.</p></div>{manage && <Link className="primary button-anchor" href="/projects?new=1#project-form">＋ New project</Link>}</section>
    {params.saved && <div className="form-success">Project changes saved.</div>}{typeof params.error === "string" && <div className="form-alert">{params.error}</div>}
    <div className="operations-grid project-operations-grid"><section className="project-card-grid">{projects.map(project => <Link href={`/projects?edit=${project.id}#project-form`} className="project-card record-project" key={project.id}><div className="project-card-top"><span className={`status-pill ${project.status === "Punch" ? "punch" : project.active ? "active" : "rework"}`}>{project.status}</span><span>{project.project_number}</span></div><h2>{project.name}</h2><p>{project.client_name} · {project.jobsite_address}</p><div className="project-meta"><span><small>MANAGER</small><strong>{project.manager_name ?? "Unassigned"}</strong></span><span><small>FOREMAN</small><strong>{project.foreman_name ?? "Unassigned"}</strong></span><span><small>ASSIGNMENTS</small><strong>{project.assigned_count}</strong></span></div></Link>)}</section>
      {manage && <section className="panel editor-panel" id="project-form"><span className="section-mark">{selected ? "EDIT PROJECT" : "NEW PROJECT"}</span><h2>{selected?.name ?? "Project details"}</h2><form action="/api/operations" method="post" className="operations-form"><input type="hidden" name="action" value="project_save"/><input type="hidden" name="id" value={selected?.id ?? ""}/><input type="hidden" name="returnTo" value={selected ? `/projects?edit=${selected.id}` : "/projects"}/><div className="form-pair"><label>Project ID<input name="projectNumber" defaultValue={selected?.project_number} required/></label><label>Status<select name="status" defaultValue={selected?.status ?? "Planning"}>{PROJECT_STATUSES.map(status => <option key={status}>{status}</option>)}</select></label></div><label>Project name<input name="name" defaultValue={selected?.name} required/></label><label>Client name<input name="clientName" defaultValue={selected?.client_name} required/></label><label>Jobsite address<input name="jobsiteAddress" defaultValue={selected?.jobsite_address} required/></label><div className="form-pair"><label>Manager<select name="managerEmployeeId" defaultValue={selected?.manager_employee_id ?? ""}><option value="">Unassigned</option>{employees.map(employee => <option value={employee.id} key={employee.id}>{employee.first_name} {employee.last_name}</option>)}</select></label><label>Foreman<select name="foremanEmployeeId" defaultValue={selected?.foreman_employee_id ?? ""}><option value="">Unassigned</option>{employees.map(employee => <option value={employee.id} key={employee.id}>{employee.first_name} {employee.last_name}</option>)}</select></label></div><div className="form-triple"><label>Start date<input type="date" name="startDate" defaultValue={selected?.start_date ?? ""}/></label><label>Estimated completion<input type="date" name="estimatedCompletionDate" defaultValue={selected?.estimated_completion_date ?? ""}/></label><label>Actual completion<input type="date" name="actualCompletionDate" defaultValue={selected?.actual_completion_date ?? ""}/></label></div><label>Project notes<textarea name="notes" defaultValue={selected?.notes ?? ""} rows={4}/></label><button className="primary" type="submit">Save project</button></form>{selected && <form action="/api/operations" method="post" className="state-form"><input type="hidden" name="action" value="state"/><input type="hidden" name="entity" value="project"/><input type="hidden" name="id" value={selected.id}/><input type="hidden" name="active" value={String(!selected.active)}/><input type="hidden" name="returnTo" value={`/projects?edit=${selected.id}`}/><button className="text-button danger-link" type="submit">{selected.active ? "Deactivate project" : "Reactivate project"}</button></form>}</section>}
    </div></div></OperationsFrame>;
}
