import { PROJECT_STATUSES, type EmployeeRecord, type ProjectRecord } from "@/lib/operations";

export function ProjectForm({ project, employees, returnTo }: { project?: ProjectRecord; employees: EmployeeRecord[]; returnTo: string }) {
  return <section className="panel editor-panel project-form-panel"><span className="section-mark">{project ? "EDIT PROJECT" : "NEW PROJECT"}</span><h2>{project?.name ?? "Project details"}</h2>
    <form action="/api/operations" method="post" className="operations-form"><input type="hidden" name="action" value="project_save"/><input type="hidden" name="id" value={project?.id ?? ""}/><input type="hidden" name="returnTo" value={returnTo}/>
      <div className="form-pair"><label>Project ID<input name="projectNumber" defaultValue={project?.project_number} required/></label><label>Status<select name="status" defaultValue={project?.status ?? "Planning"}>{PROJECT_STATUSES.map(status => <option key={status}>{status}</option>)}</select></label></div>
      <label>Project name<input name="name" defaultValue={project?.name} required/></label><label>Client name<input name="clientName" defaultValue={project?.client_name} required/></label><label>Jobsite address<input name="jobsiteAddress" defaultValue={project?.jobsite_address} required/></label>
      <div className="form-pair"><label>Manager<select name="managerEmployeeId" defaultValue={project?.manager_employee_id ?? ""}><option value="">Unassigned</option>{employees.map(employee => <option value={employee.id} key={employee.id}>{employee.first_name} {employee.last_name}</option>)}</select></label><label>Foreman<select name="foremanEmployeeId" defaultValue={project?.foreman_employee_id ?? ""}><option value="">Unassigned</option>{employees.map(employee => <option value={employee.id} key={employee.id}>{employee.first_name} {employee.last_name}</option>)}</select></label></div>
      <div className="form-triple"><label>Start date<input type="date" name="startDate" defaultValue={project?.start_date ?? ""}/></label><label>Estimated completion<input type="date" name="estimatedCompletionDate" defaultValue={project?.estimated_completion_date ?? ""}/></label><label>Actual completion<input type="date" name="actualCompletionDate" defaultValue={project?.actual_completion_date ?? ""}/></label></div>
      <label>Project notes<textarea name="notes" defaultValue={project?.notes ?? ""} rows={4}/></label><button className="primary" type="submit">Save project</button>
    </form>
    {project && <form action="/api/operations" method="post" className="state-form"><input type="hidden" name="action" value="state"/><input type="hidden" name="entity" value="project"/><input type="hidden" name="id" value={project.id}/><input type="hidden" name="active" value={String(!project.active)}/><input type="hidden" name="returnTo" value={returnTo}/><button className="text-button danger-link" type="submit">{project.active ? "Deactivate project" : "Reactivate project"}</button></form>}
  </section>;
}
