import Link from "next/link";
import { OperationsFrame } from "@/components/OperationsFrame";
import { requireAuth } from "@/lib/auth/session";
import { can } from "@/lib/auth/policy";
import { listCrews, listEmployees, operationScope } from "@/lib/operations";

export const dynamic = "force-dynamic";

export default async function CrewsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const auth = await requireAuth();
  if (!operationScope(auth, "employees.view")) return <OperationsFrame auth={auth} active="/crews"><div className="page"><div className="form-alert">You do not have permission to view crews.</div></div></OperationsFrame>;
  const [crews, employees, params] = await Promise.all([listCrews(auth), listEmployees(auth), searchParams]);
  const manage = can(auth, "employees.manage");
  const selected = crews.find(crew => crew.id === (typeof params.crew === "string" ? params.crew : ""));
  return <OperationsFrame auth={auth} active="/crews"><div className="page operations-page"><section className="welcome page-title"><div><p className="eyebrow">REUSABLE TEAMS</p><h1>Crews</h1><p>Assign a whole crew now and retain individual employee overrides later.</p></div>{manage && <Link className="primary button-anchor" href="/crews?new=1#crew-form">＋ New crew</Link>}</section>
    {params.saved && <div className="form-success">Crew changes saved.</div>}{typeof params.error === "string" && <div className="form-alert">{params.error}</div>}
    <div className="operations-grid"><section className="panel record-list">{crews.map(crew => <Link href={`/crews?crew=${crew.id}#crew-form`} className="record-row" key={crew.id}><span className="crew-badge navy">{crew.name.split(" ").map(part => part[0]).join("").slice(0,2)}</span><span><strong>{crew.name}</strong><small>{crew.foreman_name ? `${crew.foreman_name}, foreman` : "No foreman assigned"}</small></span><span className="count">{crew.member_count}</span><b>›</b></Link>)}</section>
      {manage && <section className="panel editor-panel" id="crew-form"><span className="section-mark">{selected ? "EDIT CREW" : "NEW CREW"}</span><h2>{selected?.name ?? "Crew details"}</h2><form action="/api/operations" method="post" className="operations-form"><input type="hidden" name="action" value="crew_save"/><input type="hidden" name="id" value={selected?.id ?? ""}/><input type="hidden" name="returnTo" value={selected ? `/crews?crew=${selected.id}` : "/crews"}/><label>Crew name<input name="name" defaultValue={selected?.name} required/></label><label>Foreman<select name="foremanEmployeeId" defaultValue={selected?.foreman_employee_id ?? ""}><option value="">Unassigned</option>{employees.map(employee => <option value={employee.id} key={employee.id}>{employee.first_name} {employee.last_name}</option>)}</select></label><button className="primary" type="submit">Save crew</button></form>{selected && <><div className="member-editor"><span className="section-mark">ACTIVE MEMBERS</span>{employees.filter(employee => selected.member_ids.includes(employee.id)).map(employee => <form action="/api/operations" method="post" className="member-row" key={employee.id}><input type="hidden" name="action" value="crew_member"/><input type="hidden" name="memberAction" value="remove"/><input type="hidden" name="crewId" value={selected.id}/><input type="hidden" name="employeeId" value={employee.id}/><input type="hidden" name="returnTo" value={`/crews?crew=${selected.id}`}/><span>{employee.first_name} {employee.last_name}</span><button className="text-button danger-link" type="submit">Remove</button></form>)}<form action="/api/operations" method="post" className="member-add"><input type="hidden" name="action" value="crew_member"/><input type="hidden" name="memberAction" value="add"/><input type="hidden" name="crewId" value={selected.id}/><input type="hidden" name="returnTo" value={`/crews?crew=${selected.id}`}/><select name="employeeId" required><option value="">Add employee…</option>{employees.filter(employee => !selected.member_ids.includes(employee.id)).map(employee => <option value={employee.id} key={employee.id}>{employee.first_name} {employee.last_name}</option>)}</select><button className="secondary compact" type="submit">Add</button></form></div><form action="/api/operations" method="post" className="state-form"><input type="hidden" name="action" value="state"/><input type="hidden" name="entity" value="crew"/><input type="hidden" name="id" value={selected.id}/><input type="hidden" name="active" value={String(!selected.active)}/><input type="hidden" name="returnTo" value={`/crews?crew=${selected.id}`}/><button className="text-button danger-link" type="submit">{selected.active ? "Deactivate crew" : "Reactivate crew"}</button></form></>}</section>}
    </div></div></OperationsFrame>;
}
