import Link from "next/link";
import { OperationsFrame } from "@/components/OperationsFrame";
import { requireAuth } from "@/lib/auth/session";
import { addDays } from "@/lib/scheduling";
import { getOrganizationClock, listClockOptions, listCorrectionRequests, listTimeEntries, timeScope } from "@/lib/timekeeping";

export const dynamic = "force-dynamic";

function minutes(value: number) {
  const hours = Math.floor(value / 60);
  const remainder = value % 60;
  return `${hours}h ${String(remainder).padStart(2, "0")}m`;
}

function timeOnly(value: Date | string | null, timeZone: string) {
  if (!value) return "—";
  return new Intl.DateTimeFormat("en-US", { timeZone, hour: "numeric", minute: "2-digit" }).format(new Date(value));
}

function dateLabel(value: string) {
  return new Intl.DateTimeFormat("en-US", { timeZone: "UTC", weekday: "short", month: "short", day: "numeric" }).format(new Date(`${value}T00:00:00Z`));
}

function localDateTime(value: Date | string | null, timeZone: string) {
  if (!value) return "";
  const parts = new Intl.DateTimeFormat("en-US", { timeZone, year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23" }).formatToParts(new Date(value));
  const part = (type: Intl.DateTimeFormatPartTypes) => parts.find(item => item.type === type)?.value ?? "";
  return `${part("year")}-${part("month")}-${part("day")}T${part("hour")}:${part("minute")}`;
}

export default async function TimePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const auth = await requireAuth();
  const params = await searchParams;
  const scope = timeScope(auth);
  if (!scope) return <OperationsFrame auth={auth} active="/time"><div className="page"><div className="form-alert">You do not have permission to view time records.</div></div></OperationsFrame>;
  const clock = await getOrganizationClock(auth);
  const startDate = addDays(clock.workDate, -13);
  const [entries, clockOptions] = await Promise.all([listTimeEntries(auth, startDate, clock.workDate), listClockOptions(auth, clock.workDate)]);
  const corrections = await listCorrectionRequests(auth, entries.map(entry => entry.id));
  const ownEntries = entries.filter(entry => entry.employee_id === auth.employeeId);
  const activeEntry = ownEntries.find(entry => entry.status === "active" && !entry.clock_out_at);
  const selected = entries.find(entry => entry.id === (typeof params.edit === "string" ? params.edit : ""));
  const canClock = Boolean(auth.employeeId && auth.permissions["time.clock"]?.allowed);
  const canEdit = Boolean(auth.permissions["time.edit"]?.allowed);
  const canApprove = Boolean(auth.permissions["time.approve"]?.allowed);
  const elapsed = activeEntry ? Math.max(0, Math.round((Date.parse(clock.nowIso) - new Date(activeEntry.clock_in_at).getTime()) / 60000)) : 0;
  return <OperationsFrame auth={auth} active="/time"><div className="page operations-page timekeeping-page">
    <section className="welcome page-title"><div><p className="eyebrow">ACTUAL LABOR</p><h1>Timekeeping</h1><p>Clock scheduled work, record breaks, resolve corrections, and approve authoritative labor records.</p></div></section>
    {params.saved && <div className="form-success">Timekeeping changes saved.</div>}{typeof params.error === "string" && <div className="form-alert">{params.error}</div>}
    <div className="timekeeping-top">
      {canClock && <section className="panel field-clock"><div className="field-clock-head"><span className="section-mark">YOUR DAY · {dateLabel(clock.workDate)}</span>{activeEntry && <span className={`live ${activeEntry.open_break_id ? "lunch" : ""}`}><i/>{activeEntry.open_break_id ? "ON BREAK" : "CLOCKED IN"}</span>}</div>{activeEntry ? <><div className="job-icon">▥</div><h2>{activeEntry.project_name}</h2><p>{timeOnly(activeEntry.clock_in_at, clock.timeZone)} clock-in · {activeEntry.break_count} break{activeEntry.break_count === 1 ? "" : "s"}</p><div className="big-clock">{minutes(elapsed)}</div><p className="clock-caption">Elapsed today</p><form action="/api/time" method="post"><button className="primary jumbo" name="action" value={activeEntry.open_break_id ? "end_break" : "start_break"} type="submit">{activeEntry.open_break_id ? "End lunch" : "Start lunch"}</button></form><form action="/api/time" method="post"><button className="secondary jumbo" name="action" value="clock_out" type="submit" disabled={Boolean(activeEntry.open_break_id)}>Clock out</button></form>{activeEntry.open_break_id && <small className="clock-warning">End lunch before clocking out.</small>}</> : <><div className="job-icon">▥</div><h2>Today’s job</h2><p>Select the scheduled assignment you are starting.</p><div className="clock-options">{clockOptions.map(option => <form action="/api/time" method="post" className="clock-option" key={`${option.schedule_entry_id ?? "project"}-${option.project_id}`}><input type="hidden" name="action" value="clock_in"/><input type="hidden" name="projectId" value={option.project_id}/><input type="hidden" name="scheduleEntryId" value={option.schedule_entry_id ?? ""}/><input type="hidden" name="workCategoryId" value={option.work_category_id ?? ""}/><span><strong>{option.project_name}</strong><small>{option.start_time ? `${option.start_time.slice(0,5)}–${option.end_time?.slice(0,5)}` : option.jobsite_address}</small></span><button className="primary" type="submit">Clock in</button></form>)}{clockOptions.length === 0 && <div className="empty-state">No scheduled or assigned project is available today. Ask your manager to update your schedule.</div>}</div></>}</section>}
      <section className="panel time-summary"><span className="section-mark">LAST 14 DAYS</span><h2>{scope === "self" ? "My time" : "Labor status"}</h2><div className="time-metrics"><span><small>RECORDS</small><strong>{entries.length}</strong></span><span><small>PAID HOURS</small><strong>{(entries.reduce((sum, entry) => sum + entry.paid_minutes, 0) / 60).toFixed(1)}</strong></span><span><small>NEEDS ACTION</small><strong>{entries.filter(entry => ["submitted","needs_correction"].includes(entry.status)).length}</strong></span></div><div className="status-breakdown">{["active","submitted","needs_correction","reviewed","approved"].map(status => <div key={status}><span className={`status-pill ${status === "approved" ? "approved" : status === "needs_correction" ? "rework" : status === "active" ? "active" : "progress"}`}>{status.replaceAll("_", " ")}</span><strong>{entries.filter(entry => entry.status === status).length}</strong></div>)}</div></section>
    </div>
    {scope !== "self" && <section className="panel time-review-panel"><div className="panel-head"><div><span className="section-mark">TEAM RECORDS</span><h2>Review and approval</h2></div></div><div className="time-table"><div className="time-table-head"><span>Employee / project</span><span>Date</span><span>In / out</span><span>Paid</span><span>OT</span><span>Status</span><span>Action</span></div>{entries.map(entry => <div className="time-table-row" key={entry.id}><span><strong>{entry.employee_name}</strong><small>{entry.project_name}</small></span><span>{dateLabel(entry.work_date)}</span><span>{timeOnly(entry.clock_in_at, clock.timeZone)}<small>{timeOnly(entry.clock_out_at, clock.timeZone)}</small></span><span>{minutes(entry.paid_minutes)}</span><span>{minutes(entry.overtime_minutes)}</span><span><span className={`status-pill ${entry.status === "approved" ? "approved" : entry.status === "needs_correction" ? "rework" : entry.status === "active" ? "active" : "progress"}`}>{entry.status.replaceAll("_", " ")}</span>{entry.pending_correction_count > 0 && <small>{entry.pending_correction_count} request</small>}</span><span className="row-actions">{canEdit && entry.status !== "exported" && <Link className="secondary compact" href={`/time?edit=${entry.id}#time-editor`}>Review</Link>}{canApprove && entry.clock_out_at && entry.employee_id !== auth.employeeId && entry.pending_correction_count === 0 && ["submitted","reviewed"].includes(entry.status) && <form action="/api/time" method="post"><input type="hidden" name="action" value="approve"/><input type="hidden" name="timeEntryId" value={entry.id}/><button className="primary compact" type="submit">Approve</button></form>}</span></div>)}</div></section>}
    <section className="panel personal-time-history"><div className="panel-head"><div><span className="section-mark">PERSONAL TIMECARD</span><h2>My recent entries</h2></div></div>{ownEntries.length ? ownEntries.map(entry => <article className="personal-time-row" key={entry.id}><div><strong>{dateLabel(entry.work_date)} · {entry.project_name}</strong><small>{timeOnly(entry.clock_in_at, clock.timeZone)}–{timeOnly(entry.clock_out_at, clock.timeZone)} · {minutes(entry.paid_minutes)} paid</small></div><span className={`status-pill ${entry.status === "approved" ? "approved" : entry.status === "needs_correction" ? "rework" : entry.status === "active" ? "active" : "progress"}`}>{entry.status.replaceAll("_", " ")}</span>{entry.clock_out_at && <details><summary>Request correction</summary><form action="/api/time" method="post" className="operations-form correction-form"><input type="hidden" name="action" value="correction_request"/><input type="hidden" name="timeEntryId" value={entry.id}/><div className="form-pair"><label>Requested clock-in<input type="datetime-local" name="requestedClockIn" defaultValue={localDateTime(entry.clock_in_at, clock.timeZone)}/></label><label>Requested clock-out<input type="datetime-local" name="requestedClockOut" defaultValue={localDateTime(entry.clock_out_at, clock.timeZone)}/></label></div><label>Reason<textarea name="reason" rows={2} required placeholder="Explain what should be corrected"/></label><button className="secondary" type="submit">Submit request</button></form></details>}</article>) : <div className="empty-state">No personal time entries in this period.</div>}</section>
    {selected && canEdit && <section className="panel time-editor" id="time-editor"><div><span className="section-mark">MANUAL CORRECTION</span><h2>{selected.employee_name} · {selected.project_name}</h2><p className="muted">All changes are recalculated and written to the audit history. Times use {clock.timeZone}.</p><form action="/api/time" method="post" className="operations-form"><input type="hidden" name="action" value="correct"/><input type="hidden" name="timeEntryId" value={selected.id}/><div className="form-pair"><label>Clock-in<input type="datetime-local" name="clockInAt" defaultValue={localDateTime(selected.clock_in_at, clock.timeZone)} required/></label><label>Clock-out<input type="datetime-local" name="clockOutAt" defaultValue={localDateTime(selected.clock_out_at, clock.timeZone)} required/></label></div><label>Reason for change<textarea name="reason" rows={3} required placeholder="For example: Employee forgot to clock out after cleanup"/></label><button className="primary" type="submit">Apply correction</button></form><div className="editor-actions">{!["approved","exported"].includes(selected.status) && <form action="/api/time" method="post"><input type="hidden" name="action" value="review"/><input type="hidden" name="timeEntryId" value={selected.id}/><button className="secondary" type="submit">Mark reviewed</button></form>}{canApprove && selected.employee_id !== auth.employeeId && selected.pending_correction_count === 0 && ["submitted","reviewed"].includes(selected.status) && <form action="/api/time" method="post"><input type="hidden" name="action" value="approve"/><input type="hidden" name="timeEntryId" value={selected.id}/><button className="primary" type="submit">Approve time</button></form>}</div></div><aside><span className="section-mark">CORRECTION REQUESTS</span>{corrections.filter(request => request.time_entry_id === selected.id).map(request => <div className="correction-request" key={request.id}><div><strong>{request.requested_by}</strong><span className={`status-pill ${request.status === "pending" ? "review" : request.status === "accepted" ? "approved" : "rework"}`}>{request.status}</span></div><p>{request.reason}</p><small>{Object.entries(request.requested_changes ?? {}).filter(([, value]) => value).map(([key, value]) => `${key}: ${String(value)}`).join(" · ")}</small>{request.status === "pending" && <form action="/api/time" method="post"><input type="hidden" name="action" value="resolve_correction"/><input type="hidden" name="requestId" value={request.id}/><button className="text-button" name="resolution" value="accepted" type="submit">Accept after correction</button><button className="text-button danger-link" name="resolution" value="rejected" type="submit">Reject</button></form>}</div>)}{corrections.every(request => request.time_entry_id !== selected.id) && <p className="muted">No correction requests for this entry.</p>}</aside></section>}
  </div></OperationsFrame>;
}
